# -*- coding: utf-8 -*-
"""app_frame.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JtbYh1eWeToq6yzcft4qExLCjkUyihFK
"""

pip install yfinance

pip install streamlit

pip install altair

pip install docx2txt

pip install yfinance

pip install PyPortfolioOpt

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &

import urllib
print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))



!npx localtunnel --port 8501

!ls